version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb-password
      MONGO_INITDB_DATABASE: your_db_name
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

  # User Service
  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5001
      MONGO_URI: mongodb://root:mongodb-password@mongo:27017/your_db_name?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      BCRYPT_ROUNDS: 10
      NOTIFICATION_SERVICE_URL: http://notification-service:5003
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - microservices-network

  # Course Service
  course-service:
    build: ./services/course-service
    container_name: course-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5002
      MONGO_URI: mongodb://root:mongodb-password@mongo:27017/your_db_name?authSource=admin
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    networks:
      - microservices-network

  # Notification Service
  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5003
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: parashuramuluchilukuri@gmail.com
      SMTP_PASS: evbkbefxufpegdaq
      FROM_EMAIL: parashuramuluchilukuri@gmail.com
      SENDER_EMAIL: parashuramuluchilukuri@gmail.com
      SENDER_PASSWORD: evbkbefxufpegdaq
    ports:
      - "5003:5003"
    networks:
      - microservices-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      REACT_APP_USER_API_URL: http://localhost:5001
      REACT_APP_COURSE_API_URL: http://localhost:5002
      REACT_APP_USER_SERVICE_URL: http://localhost:5001
      REACT_APP_COURSE_SERVICE_URL: http://localhost:5002
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - course-service
    networks:
      - microservices-network

volumes:
  mongo_data:

networks:
  microservices-network:
    driver: bridge